MOEN-8794 MOEN-9805 MOEN-9804 version 11 upgrade
moengage/Flutter-SDK pull request #11
Opened 2021-02-12 13:14 UTC by arshiya-moengage

Android:
* MOEN-8794: Flutter set method call handler to null when the engine is in detached state
* MOEN-9805: Update Flutter Inbox Plugin with SDK version v6
* MOEN-9804: Update Flutter Core Plugin with native SDK v11

Common:
* Added Push Token callback

2021-02-15 07:33 UTC, umangmoe requested changes

2021-02-15 07:33 UTC, umangmoe commented on core/lib/utils.dart
> +PushToken pushTokenFromJson(dynamic methodCallArgs) {
See if we can avoid nulls with default values or something else. Dart has introduced null safety support similar to Kotlin and might be a problem if the client enables null safety.

2021-02-15 07:33 UTC, umangmoe commented on core/android/build.gradle
> +        mavenLocal()
remove this.

2021-02-19 13:05 UTC, umangmoe commented
@arshiya-moengage  Add API similar to the one here - https://github.com/moengage/MoEngage-Unity-SDK/blob/master/Android/android-unity-wrapper/unity-wrapper/src/main/java/com/moengage/unity/wrapper/MoEInitializer.java#L52

2021-02-22 16:13 UTC, umangmoe commented on core/lib/push_token.dart
> +  String pushService;
Use enum

2021-02-23 03:16 UTC, umangmoe commented on inbox/android/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip
any reason this was changed from `all` to `bin`

2021-02-23 05:03 UTC, arshiya-moengage commented on core/lib/push_token.dart
> +  String pushService;
done

2021-02-23 05:07 UTC, arshiya-moengage commented on inbox/android/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip
Got overwritten while rebasing, fixed now.

2021-02-23 07:35 UTC, umangmoe approved these changes

2021-02-23 07:35 UTC, merged