MOEN-30132 Non Intrusive Nudges Support
moengage/Flutter-SDK pull request #110
Opened 2024-02-26 12:49 UTC by kkgowtham-engg-sdk

### Jira Ticket
https://moengagetrial.atlassian.net/browse/MOEN-30132

### Description
Non Intrusive Nudges Support

2024-03-06 06:18 UTC, RakshithaAcharya requested changes

2024-03-06 06:18 UTC, RakshithaAcharya commented on core/moengage_flutter_platform_interface/lib/src/moengage_flutter_platform_interface.dart
> +      throw UnimplementedError('showNudge() not implemented for Platform');
@msoumya-engg-sdk what is the purpose of this method

2024-03-06 06:30 UTC, msoumya-engg-sdk commented on core/moengage_flutter_platform_interface/lib/src/moengage_flutter_platform_interface.dart
> +      throw UnimplementedError('showNudge() not implemented for Platform');
This is the interface method which is overridden by each platform with platform specific implementation.

2024-03-06 06:37 UTC, RakshithaAcharya approved these changes

2024-03-07 09:58 UTC, arshiya-moengage commented on cards/moengage_cards_android/CHANGELOG.md
> +- Support for `moe-android-sdk` version `12.10.04` and above
The version has to be updated

2024-03-07 09:58 UTC, arshiya-moengage commented on cards/moengage_cards_android/android/build.gradle
> +    compileOnly("com.moengage:moe-android-sdk:12.10.04")
version is outdated

2024-03-07 09:58 UTC, arshiya-moengage commented on core/moengage_flutter_android/CHANGELOG.md
> +- Support for `moe-android-sdk` version `12.10.04` and above
update the version

2024-03-07 09:58 UTC, arshiya-moengage commented on core/moengage_flutter_android/android/build.gradle
> +    compileOnly("com.moengage:moe-android-sdk:12.10.04")
update the versions

2024-03-07 09:58 UTC, arshiya-moengage commented on core/moengage_flutter_web/lib/moengage_flutter_web.dart
Revert these changes

2024-03-07 09:58 UTC, arshiya-moengage commented on example/android/settings.gradle
> +                from("com.moengage:android-dependency-catalog:3.2.5")
Update the version

2024-03-07 09:58 UTC, arshiya-moengage commented on geofence/moengage_geofence_android/CHANGELOG.md
> +- Support for `moe-android-sdk` version `12.10.04` and above
update the native version

2024-03-07 09:58 UTC, arshiya-moengage commented on geofence/moengage_geofence_android/android/build.gradle
> +    compileOnly("com.moengage:moe-android-sdk:12.10.04")
update the version

2024-03-07 09:58 UTC, arshiya-moengage commented on inbox/moengage_inbox_android/CHANGELOG.md
> +- Support for `moe-android-sdk` version `12.10.04` and above
update version

2024-03-07 09:58 UTC, arshiya-moengage commented on inbox/moengage_inbox_android/android/build.gradle
> +    compileOnly("com.moengage:moe-android-sdk:12.10.04")
update version

2024-03-07 10:23 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_web/lib/moengage_flutter_web.dart
Reverted.

2024-03-07 10:37 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_android/android/build.gradle
> +    api("com.moengage:plugin-base:4.0.0")
TODO: Confirm Plugin Base Versions before Merging

2024-03-07 10:38 UTC, kkgowtham-engg-sdk commented on inbox/moengage_inbox_android/android/build.gradle
> +    compileOnly("com.moengage:moe-android-sdk:12.10.04")
Updated

2024-03-07 10:38 UTC, kkgowtham-engg-sdk commented on geofence/moengage_geofence_android/android/build.gradle
> +    compileOnly("com.moengage:moe-android-sdk:12.10.04")
Updated

2024-03-07 10:38 UTC, kkgowtham-engg-sdk commented on geofence/moengage_geofence_android/CHANGELOG.md
> +- Support for `moe-android-sdk` version `12.10.04` and above
Updated

2024-03-07 10:38 UTC, kkgowtham-engg-sdk commented on example/android/settings.gradle
> +                from("com.moengage:android-dependency-catalog:3.2.5")
updated

2024-03-07 10:39 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_android/android/build.gradle
> +    compileOnly("com.moengage:moe-android-sdk:12.10.04")
Updated

2024-03-07 10:39 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_android/CHANGELOG.md
> +- Support for `moe-android-sdk` version `12.10.04` and above
Updated

2024-03-07 10:39 UTC, kkgowtham-engg-sdk commented on cards/moengage_cards_android/android/build.gradle
> +    compileOnly("com.moengage:moe-android-sdk:12.10.04")
Updated

2024-03-07 10:39 UTC, kkgowtham-engg-sdk commented on cards/moengage_cards_android/CHANGELOG.md
> +- Support for `moe-android-sdk` version `12.10.04` and above
Updated

2024-03-15 05:43 UTC, merged