[MOEN-31747] flutter platform core and web-specific changes for object support in user and event attributes
moengage/Flutter-SDK pull request #120
Opened 2024-05-24 07:37 UTC by adityagupta-7

### Jira Ticket
https://moengagetrial.atlassian.net/browse/MOEN-31747
### Description
flutter platform core and web-specific changes for object support in user and event attributes

2024-05-28 07:09 UTC, nawazMoEngage submitted a review, later dismissed

2024-05-30 04:41 UTC, msoumya-engg-sdk requested changes

2024-05-30 04:41 UTC, msoumya-engg-sdk commented on core/moengage_flutter_platform_interface/lib/src/model/properties.dart
> +import '../../moengage_flutter_platform_interface.dart';
Verify if this import needed

2024-05-30 06:16 UTC, adityagupta-7 commented on core/moengage_flutter_web/lib/moengage_flutter_web.dart
> +import 'package:flutter/foundation.dart';
removed these imports

2024-05-30 06:17 UTC, adityagupta-7 commented on core/moengage_flutter_web/lib/moengage_flutter_web.dart
> +    Timer(const Duration(seconds: 5), anyFunction);
commented this line and added another comment about its usage

2024-05-30 06:17 UTC, adityagupta-7 commented on core/moengage_flutter_platform_interface/lib/src/model/properties.dart
> +import '../../moengage_flutter_platform_interface.dart';
removed the second import.. first one is required

2024-05-30 06:30 UTC, msoumya-engg-sdk commented
@adityagupta-7 please add entry to changelogs for changes packages, rest everything are fine

2024-05-30 07:46 UTC, msoumya-engg-sdk submitted a review, later dismissed

2024-06-12 07:06 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_web/lib/moengage_flutter_web.dart
> +    // uncomment the below line if moengage web sdk initialisation issue occurs
I think at any time we shouldn't have this generic for all the clients. It should be responsible for the client to call `initialise` at delay based on their load time.

We can just call out in documentation and update Readme.md file [here](https://github.com/moengage/Flutter-SDK/pull/115/files).

2024-06-17 02:24 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_web/lib/utils.dart
> +  }
I think we can remove typecasting to `Object` since all the dart classes have base class as `Object`.

2024-06-17 11:28 UTC, adityagupta-7 commented on core/moengage_flutter_web/lib/utils.dart
> +  }
done

2024-06-17 11:29 UTC, adityagupta-7 commented on core/moengage_flutter_web/lib/moengage_flutter_web.dart
> +    // uncomment the below line if moengage web sdk initialisation issue occurs
added this piece of information in README file and removed the comments from the file

2024-06-24 12:12 UTC, kkgowtham-engg-sdk submitted a review, later dismissed

2024-07-01 10:10 UTC, kkgowtham-engg-sdk approved these changes

2024-07-02 12:05 UTC, kkgowtham-engg-sdk submitted a review, later dismissed

2024-07-03 04:32 UTC, kkgowtham-engg-sdk commented
TODO: Update the Plugin Base version before Release

2024-07-03 08:52 UTC, umangmoe approved these changes

2024-07-03 08:54 UTC, merged