MOEN-33220: Added boolean user attribute tracking customization in initialization API
moengage/Flutter-SDK pull request #133
Opened 2024-07-29 09:32 UTC by msoumya-engg-sdk

### Jira Ticket

https://moengagetrial.atlassian.net/browse/MOEN-33220

### Description

Added boolean user attribute tracking customization in initialization API

2024-07-29 10:34 UTC, RakshithaAcharya requested changes

2024-07-29 10:34 UTC, RakshithaAcharya commented on geofence/moengage_geofence_ios/CHANGELOG.md
> +# Next Release
@msoumya-engg-sdk Update the sample with initialization code

2024-07-29 11:49 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_platform_interface/lib/src/model/moe_init_config.dart
> +      : analyticsConfig = analyticsConfig ?? AnalyticsConfig.defaultConfig();
I think this way is better for handling the Mandatory constructor param.
Since we are touching this file, can we move `PushConfig` also to this way.

2024-07-29 12:14 UTC, kkgowtham-engg-sdk approved these changes

2024-07-30 06:03 UTC, arshiya-moengage submitted a review, later dismissed

2024-07-30 06:23 UTC, kkgowtham-engg-sdk submitted a review, later dismissed

2024-08-07 06:58 UTC, RakshithaAcharya approved these changes

2024-08-07 06:58 UTC, merged