Moen 10991 sound null safety
moengage/Flutter-SDK pull request #18
Opened 2021-05-04 07:03 UTC by arshiya-moengage

2021-05-06 08:43 UTC, umangmoe requested changes

2021-05-07 05:18 UTC, arshiya-moengage commented on core/lib/moengage_flutter.dart
> +  void trackEvent(String eventName, MoEProperties? eventAttributes) {
fixed

2021-05-07 05:18 UTC, arshiya-moengage commented on core/lib/moe_android_core.dart
> +  void trackEvent(String eventName, MoEProperties? eventAttributes) {
fixed

2021-05-07 05:20 UTC, arshiya-moengage commented on core/lib/moengage_flutter.dart
> +          _onPushTokenGenerated!(pushToken);
fixed

2021-05-07 05:20 UTC, arshiya-moengage commented on core/lib/utils.dart
> +    String eventName, MoEProperties? eventAttributes) {
fixed

2021-05-07 05:20 UTC, arshiya-moengage commented on core/lib/moengage_flutter.dart
>          if (pushToken != null) {
fixed

2021-05-07 05:31 UTC, arshiya-moengage commented on core/lib/moe_push_service.dart
> +      default: throw Exception("error: MoEPushService.fromString() : $pushService is not a valid pushService type.");
Done

2021-05-11 10:30 UTC, ChengappaMoEngage commented on inbox/lib/payload_transformer.dart
> -  return null;
Here Return Null should be present, right?
If the switch case is not satisfied, we should return null here

2021-05-11 10:31 UTC, ChengappaMoEngage commented on inbox/lib/payload_transformer.dart
> -  return null;
Same here return null should be present.
If the switch case is not satisfied, we should return null here

2021-05-11 12:13 UTC, arshiya-moengage commented on inbox/lib/payload_transformer.dart
> -  return null;
Fixed.
Had removed it by mistake, Flutter code analysis had marked this line as dead code.

2021-05-11 12:13 UTC, arshiya-moengage commented on inbox/lib/payload_transformer.dart
> -  return null;
Fixed.
Had removed it by mistake, Flutter code analysis had marked this line as dead code.

2021-05-11 12:36 UTC, ChengappaMoEngage approved these changes
LGTM

2021-05-12 05:31 UTC, umangmoe approved these changes

2021-05-12 05:31 UTC, merged