MOEN-8735 Flutter Plugin Update
moengage/Flutter-SDK pull request #6
Opened 2020-10-21 09:31 UTC by arshiya-moengage

2020-10-21 09:52 UTC, umangmoe commented on android/build.gradle
> +    ext.kotlin_version = '1.4.10'
use 1.3.61 instead to be consistent with native SDK

2020-10-21 09:54 UTC, umangmoe commented on android/src/main/kotlin/com/moengage/flutter/MoEInitializer.kt
> +                Logger.v("$tag initialize() : Will try to initialize the sdk.")
fix the formatting.

2020-10-21 11:17 UTC, umangmoe requested changes

2020-10-21 11:17 UTC, umangmoe commented on lib/properties.dart
>    Map<String, dynamic> getEventAttributeJson() {
Change method name for consistency

2020-10-21 11:17 UTC, umangmoe commented on lib/push_campaign.dart
> +        "clickedAction:" + clickedAction.toString() + "\n" +
`toString()` on null object can lead to Null Pointer Exception

2020-10-21 11:17 UTC, umangmoe commented on lib/utils.dart
> +            "error: inAppCampaignFromMap : campaignId or campaignName is empty.");
At this point only the campaign id is null let the message convey that instead of assuming the campaign name might be null as well.

2020-10-21 11:17 UTC, umangmoe commented on lib/utils.dart
> +            "error: inAppCampaignFromMap : campaignId or campaignName is empty.");
fix the error message as mentioned above

2020-10-21 11:17 UTC, umangmoe commented on lib/utils.dart
> +      if (inAppCampaignMap.containsKey(keySelfHandled)) {
Parsing for self-handled isn't correct check and fix. The keys are messed up.
Also, remove the C-style declarations.

2020-10-21 11:17 UTC, umangmoe commented on lib/inapp_campaign.dart
> +  InAppCampaign(this.campaignId, this.campaignName, this.platform,
```dart
class InAppCampaign {

  String campaignId;
  String campaignName;
  String platform;
  NavigationAction navigationAction;
  SelfHandled selfHandled;
  CustomAction customAction;

  InAppCampaign(this.campaignId, this.campaignName, this.platform);
}
```
model could be like this. since other params are non-mandatory. Will clean up the parsing code in utils as well.
@ChengappaMoEngage thoughts?

2020-10-21 11:17 UTC, umangmoe commented on lib/inapp_navigation.dart
> +import 'constants.dart';
change the file name to `navigation_action.dart` to allow reuse for push and other features in future.

2020-10-21 11:26 UTC, umangmoe commented on android/build.gradle
> +    implementation "androidx.core:core-ktx:1.3.2"
Why is ktx required? I don't think we are using support library in the 1st place

2020-10-21 11:27 UTC, umangmoe commented on android/src/main/kotlin/com/moengage/flutter/MoEInitializer.kt
> +package android.src.main.kotlin.com.moengage.flutter
incorrect package name

2020-10-21 11:32 UTC, umangmoe commented on android/src/main/kotlin/com/moengage/flutter/EventEmitterImpl.kt
> +            Logger.e("$tag emitInAppEvent() : campaignJSON: $campaign")
Incorrect log level

2020-10-21 11:35 UTC, umangmoe commented on android/src/main/kotlin/com/moengage/flutter/EventEmitterImpl.kt
> +            emit(eventType, payload.getJSONObject("payload"))
Complete JSON should be passed why just `payload?`

2020-10-21 11:36 UTC, umangmoe commented on android/src/main/kotlin/com/moengage/flutter/MoEInitializer.kt
> +        private const val tag: String = "${MODULE_TAG}MoEInitializer}"
remove additional `}`

2020-10-21 11:40 UTC, umangmoe commented on android/src/main/kotlin/com/moengage/flutter/MoEngageFlutterPlugin.kt
> +            Handler(Looper.getMainLooper()).post { channel?.invokeMethod(methodName, message) }
try catch required around invokeMethod() api call. Called on the main thread will crash the application if something goes wrong.

2020-10-21 11:45 UTC, umangmoe commented on example/lib/main.dart
> +                    _moengagePlugin.trackEvent("testEvent", null);
use `_moengagePlugin.trackEvent("testEvent", MoEProperties());`

2020-10-21 11:52 UTC, umangmoe commented on pubspec.yaml
> +#author: MoEngage Inc<mobiledevs@moengage.com>
remove this line instead of commenting.

2020-10-21 15:53 UTC, arshiya-moengage commented on android/build.gradle
> +    ext.kotlin_version = '1.4.10'
done

2020-10-21 15:54 UTC, arshiya-moengage commented on lib/inapp_campaign.dart
> +    inAppMap[keyCampaignId] = this.campaignId;
done

2020-10-21 15:58 UTC, arshiya-moengage commented on lib/inapp_navigation.dart
> +      keyNavigationType: this.navigationType,
keeping this format for mandatory fields in in-app, adding rest with null check

2020-10-21 16:02 UTC, arshiya-moengage commented on lib/moengage_flutter.dart
> +  void setUpPushCallbacks(PushCallbackHandler onPushClick) {
push has only on click action

2020-10-21 16:03 UTC, arshiya-moengage commented on lib/utils.dart
> +            "error: inAppCampaignFromMap : campaignId or campaignName is empty.");
add one for empty as well?

2020-10-21 16:05 UTC, arshiya-moengage commented on lib/utils.dart
> +            "error: inAppCampaignFromMap : campaignId or campaignName is empty.");
ignore, done

2020-10-21 16:05 UTC, arshiya-moengage commented on lib/utils.dart
> +            "error: inAppCampaignFromMap : campaignId or campaignName is empty.");
done

2020-10-21 16:08 UTC, arshiya-moengage commented on lib/inapp_campaign.dart
> +  InAppCampaign(this.campaignId, this.campaignName, this.platform,
null can be passed, otherwise will have add setters for the rest of the fileds

2020-10-21 16:10 UTC, arshiya-moengage commented on lib/inapp_navigation.dart
> +import 'constants.dart';
done

2020-10-21 16:10 UTC, arshiya-moengage commented on android/src/main/kotlin/com/moengage/flutter/MoEInitializer.kt
> +package android.src.main.kotlin.com.moengage.flutter
fixed

2020-10-21 16:21 UTC, arshiya-moengage commented on lib/utils.dart
> +      if (inAppCampaignMap.containsKey(keySelfHandled)) {
done

2020-10-21 16:22 UTC, arshiya-moengage commented on android/build.gradle
> +    implementation "androidx.core:core-ktx:1.3.2"
removed

2020-10-21 16:23 UTC, arshiya-moengage commented on android/src/main/kotlin/com/moengage/flutter/EventEmitterImpl.kt
> +            Logger.e("$tag emitInAppEvent() : campaignJSON: $campaign")
fixed

2020-10-21 16:25 UTC, arshiya-moengage commented on android/src/main/kotlin/com/moengage/flutter/EventEmitterImpl.kt
> +            emit(eventType, payload.getJSONObject("payload"))
fixed

2020-10-21 16:25 UTC, arshiya-moengage commented on android/src/main/kotlin/com/moengage/flutter/MoEInitializer.kt
> +        private const val tag: String = "${MODULE_TAG}MoEInitializer}"
fixed

2020-10-21 16:27 UTC, arshiya-moengage commented on android/src/main/kotlin/com/moengage/flutter/MoEngageFlutterPlugin.kt
> +            Handler(Looper.getMainLooper()).post { channel?.invokeMethod(methodName, message) }
done

2020-10-21 16:28 UTC, arshiya-moengage commented on example/lib/main.dart
> +                    _moengagePlugin.trackEvent("testEvent", null);
done

2020-10-21 16:29 UTC, arshiya-moengage commented on pubspec.yaml
> +#author: MoEngage Inc<mobiledevs@moengage.com>
done

2020-10-21 16:30 UTC, arshiya-moengage commented on android/src/main/kotlin/com/moengage/flutter/EventEmitterImpl.kt
> +            MoEngageFlutterPlugin.sendOrQueueCallback(methodName, payload.toString())
this api is removed

2020-10-22 04:28 UTC, arshiya-moengage commented on lib/inapp_campaign.dart
> +  InAppCampaign(this.campaignId, this.campaignName, this.platform,
while creating an object I will have set the values separately while others will be set via constructor

2020-10-22 05:12 UTC, umangmoe commented on lib/inapp_campaign.dart
> +  InAppCampaign(this.campaignId, this.campaignName, this.platform,
That's standard practice for optional fields right. That is how optional fields are generally implemented. Overloaded constructors or mandatory fields in the constructor and optional ones set on the object.

2020-10-22 05:34 UTC, umangmoe commented on lib/moe_android.dart
> +
name the file `moe_android_core.dart`

2020-10-22 05:35 UTC, umangmoe requested changes

2020-10-22 05:35 UTC, umangmoe commented on lib/moe_android.dart
> +class MoEAndroid {
`MoEAndroidCore`

2020-10-23 04:46 UTC, arshiya-moengage commented on android/src/main/kotlin/com/moengage/flutter/EventEmitterImpl.kt
> +            emit(eventType, payload.getJSONObject("payload"))
payload is the complete event, the other parameter is event type which used to determine the call type. Event type isn not passed to client

2020-10-23 04:52 UTC, arshiya-moengage commented on android/src/main/kotlin/com/moengage/flutter/EventEmitterImpl.kt
> +            MoEngageFlutterPlugin.sendOrQueueCallback(methodName, payload.toString())
queuing is removed from android plugin since it's handled in base plugin, send callback is invoked directly which cannot be moved to EventEmitterImpl since it requires channel and no point in passing channel instance to the emitter.

2020-10-23 16:25 UTC, merged