MOEN-24218: Implement cards flutter for ios
moengage/Flutter-SDK pull request #86
Opened 2023-06-23 08:26 UTC by msoumya-engg-sdk

### Jira Ticket

https://moengagetrial.atlassian.net/browse/MOEN-24218

### Description

iOS specific changes for flutter cards.

2023-06-23 09:38 UTC, RakshithaAcharya requested changes

2023-06-23 09:38 UTC, RakshithaAcharya commented on cards/ios/Classes/MoEngageCardSyncListner.swift
> +        guard let jsonData = try? JSONSerialization.data(withJSONObject: data),
@msoumya-engg-sdk lets reuse the method in native .. I see its being repeated in multiple places

2023-06-26 13:20 UTC, msoumya-engg-sdk commented on cards/ios/Classes/MoEngageCardSyncListner.swift
> +        guard let jsonData = try? JSONSerialization.data(withJSONObject: data),
@RakshithaAcharya  removed duplication from the two places used in cards plugin.

2023-06-27 04:49 UTC, RakshithaAcharya approved these changes

2023-06-27 06:24 UTC, kkgowtham-engg-sdk approved these changes

2023-07-11 07:08 UTC, merged