MOEN-24836 Federated Plugin Implementation
moengage/Flutter-SDK pull request #91
Opened 2023-08-02 04:13 UTC by kkgowtham-engg-sdk

### Jira Ticket
https://moengagetrial.atlassian.net/browse/MOEN-24836

### Description
Federated Plugin Implementation

2023-08-03 09:28 UTC, nawazMoEngage approved these changes

2023-08-04 11:36 UTC, msoumya-engg-sdk requested changes

2023-08-04 11:36 UTC, msoumya-engg-sdk commented on cards/moengage_cards/lib/src/moengage_cards.dart
> +  Future<void> onCardsSectionLoaded(CardsSyncListener cardsSyncListener) async {
Any reason this method is async, since there is no await call?

2023-08-11 00:12 UTC, kkgowtham-engg-sdk commented on cards/moengage_cards/lib/src/moengage_cards.dart
> +  Future<void> onCardsSectionLoaded(CardsSyncListener cardsSyncListener) async {
Updated

2023-08-16 04:15 UTC, msoumya-engg-sdk approved these changes
LGTM

2023-08-23 12:37 UTC, arshiya-moengage commented on core/moengage_flutter_platform_interface/lib/src/model/push/push_campaign.dart
>    Map<String, dynamic> toMap() {
I couldn't find the method usage, please check

2023-08-23 12:37 UTC, arshiya-moengage commented on core/moengage_flutter_platform_interface/lib/src/model/geo_location.dart
> +  Map<String, double> toMap() {
This is showing missing documentation for public api lint error

2023-08-23 12:37 UTC, arshiya-moengage commented on core/moengage_flutter_platform_interface/lib/src/model/properties.dart
add documentation to `getEventAttributeJson()` to resolve lint warning

2023-08-23 12:37 UTC, arshiya-moengage commented on core/moengage_flutter_platform_interface/lib/src/constants.dart
shouldn't this file be internal? Everything apart from the models(utils etc) and the public interface should be in internal

2023-08-24 09:05 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter/lib/src/moengage_flutter.dart
> +  /// Sets Push Click Callback Handler
Updated

2023-08-24 09:06 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter/lib/src/moengage_flutter.dart
> +  ///Set the current context for the given user.
Updated

2023-08-24 09:06 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter/lib/src/moengage_flutter.dart
> +  /// Ensure self handled in-app listener is set before you call this.
Updated

2023-08-24 09:07 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter/lib/src/moengage_flutter.dart
> +  ///Optionally opt-in data tracking.
Updated

2023-08-24 09:08 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter/lib/src/moengage_flutter.dart
> +  /// Pass FCM Push Token to the MoEngage SDK.
Updated

2023-08-24 09:09 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter/lib/src/moengage_flutter.dart
> +  /// API to enable SDK usage.
Updated

2023-08-24 09:12 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_platform_interface/lib/src/model/inapp/navigation_type.dart
>    String get asString {
Removed

2023-08-24 09:12 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_platform_interface/lib/src/model/push/push_campaign.dart
>    Map<String, dynamic> toMap() {
Removed

2023-08-24 09:13 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_platform_interface/lib/src/model/properties.dart
Updated

2023-08-24 09:13 UTC, kkgowtham-engg-sdk commented
> 1. The `moengage_flutter_platform_interface` folder has to be restructured to follow the standard structuring we have in other repos.
> 2. The comments in the public apis is missing the param description. Please fix that

Updated

2023-08-24 09:13 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_platform_interface/lib/src/model/geo_location.dart
> +  Map<String, double> toMap() {
Updated

2023-08-24 09:16 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_ios/ios/Classes/MoEngageFlutterPluginInfo.swift
> + static let kVersion = "1.0.0"
Since the IOS folder moved to a separate package, the version will be starting from 1.0.0 as expected.

2023-08-24 09:16 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter/lib/src/moengage_flutter.dart
> +  /// Notify the SDK on notification permission granted to the application.
Updated

2023-08-24 09:16 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter/lib/src/moengage_flutter.dart
> +  ///API to disable Advertising Id tracking for the account configured as default.
Updated

2023-08-24 09:17 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter/lib/src/moengage_flutter.dart
> +  ///API to enable Android-id tracking for the given instance.
Updated

2023-08-24 09:17 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter/lib/src/moengage_flutter.dart
> +  void onOrientationChanged() {
Updated

2023-08-24 13:22 UTC, kkgowtham-engg-sdk commented on cards/moengage_cards_platform_interface/lib/src/internal/cards_controller.dart
Fixed

2023-08-24 13:22 UTC, kkgowtham-engg-sdk commented on cards/moengage_cards_platform_interface/lib/src/internal/cards_controller.dart
> +        '$_tag _handler(): Error: ${call} has an Exception:',
Updated

2023-08-24 13:23 UTC, kkgowtham-engg-sdk commented on cards/moengage_cards_platform_interface/lib/src/internal/cards_controller.dart
> +        error: err,
Updated

2023-08-24 13:23 UTC, kkgowtham-engg-sdk commented on cards/moengage_cards_platform_interface/lib/moengage_cards_platform_interface.dart
> +  /// Note: This API should be used when the cards screen is invisible to user
Updated

2023-08-24 13:23 UTC, kkgowtham-engg-sdk commented on cards/moengage_cards_platform_interface/lib/src/internal/payload_mapper.dart
>      default:
Updated

2023-08-24 13:23 UTC, kkgowtham-engg-sdk commented on cards/moengage_cards_platform_interface/lib/src/internal/payload_mapper.dart
Updated

2023-08-24 13:23 UTC, kkgowtham-engg-sdk commented on cards/moengage_cards_platform_interface/lib/src/internal/payload_mapper.dart
> +      return '';
Updated

2023-08-24 13:23 UTC, kkgowtham-engg-sdk commented on cards/moengage_cards_platform_interface/lib/src/method_channel_moengage_cards.dart
Updated

2023-08-24 13:24 UTC, kkgowtham-engg-sdk commented on cards/moengage_cards_platform_interface/lib/src/model/action/action.dart
>    //Abstract Function, should be overridden by Implementation Class
Updated

2023-08-24 13:24 UTC, kkgowtham-engg-sdk commented on cards/moengage_cards_platform_interface/lib/src/model/action/action.dart
> +  Action(this.actionType);
Updated

2023-08-24 13:24 UTC, kkgowtham-engg-sdk commented on cards/moengage_cards_platform_interface/lib/src/model/action/navigation_action.dart
>  class NavigationAction extends Action {
Updated

2023-08-24 13:24 UTC, kkgowtham-engg-sdk commented on cards/moengage_cards_platform_interface/lib/src/model/style/button_style.dart
>    ButtonStyle({required String backgroundColor, required this.fontSize})
Updated

2023-08-24 13:25 UTC, kkgowtham-engg-sdk commented on cards/moengage_cards/lib/src/moengage_cards.dart
Updated

2023-08-24 13:26 UTC, kkgowtham-engg-sdk commented on cards/moengage_cards/test/moengage_cards_test.dart
Test cases are added only in respective platform interface packages, as core logic and models are present there. 
So adding in all pakcages wont be required.

2023-08-25 05:10 UTC, arshiya-moengage commented on geofence/moengage_geofence_platform_interface/lib/src/internal/moe_geofence_utils.dart
>  Map<String, dynamic> getAccountMeta(String appId) {
Why can't we use the `getAccountMeta()` defined in core, since all other modules depend on it?

2023-08-25 05:10 UTC, arshiya-moengage commented on inbox/moengage_inbox_platform_interface/lib/src/model/media_type.dart
> +import '../moengage_inbox_platform_interface.dart';
unused import

2023-08-25 05:10 UTC, arshiya-moengage commented on inbox/moengage_inbox_platform_interface/lib/src/model/media_type.dart
>  extension MediaTypeExt on MediaType {
missing documentation

2023-08-25 05:10 UTC, arshiya-moengage commented on inbox/moengage_inbox_platform_interface/lib/src/model/text_content.dart
> +import '../moengage_inbox_platform_interface.dart';
unused import

2023-08-25 05:19 UTC, kkgowtham-engg-sdk commented on inbox/moengage_inbox_platform_interface/lib/src/model/text_content.dart
> +import '../moengage_inbox_platform_interface.dart';
Updated

2023-08-25 05:20 UTC, kkgowtham-engg-sdk commented on inbox/moengage_inbox_platform_interface/lib/src/model/media_type.dart
>  extension MediaTypeExt on MediaType {
Updated

2023-08-25 05:20 UTC, kkgowtham-engg-sdk commented on inbox/moengage_inbox_platform_interface/lib/src/model/media_type.dart
> +import '../moengage_inbox_platform_interface.dart';
Updated

2023-08-25 05:21 UTC, kkgowtham-engg-sdk commented on geofence/moengage_geofence_platform_interface/lib/src/internal/moe_geofence_utils.dart
>  Map<String, dynamic> getAccountMeta(String appId) {
Removed And Reused core method

2023-08-25 05:21 UTC, kkgowtham-engg-sdk commented on geofence/moengage_geofence_android/pubspec_overrides.yaml
> +  moengage_flutter_android:
Updated

2023-08-25 05:43 UTC, arshiya-moengage commented on cards/moengage_cards_android/android/build.gradle
> +    compileOnly("com.moengage:plugin-base:3.3.2")
why is plugin-base dependency required here? since cards plugin already has the plugin base dependency.

2023-08-25 06:41 UTC, kkgowtham-engg-sdk commented on cards/moengage_cards_android/android/build.gradle
> +    compileOnly("com.moengage:plugin-base:3.3.2")
We are using one method from core plugin base. So we need compileOnly dependency here. 
Cards Plugin has only compileOnly dependency of the plugin base core.

2023-09-13 04:41 UTC, merged