Delete User Details API
moengage/Flutter-SDK pull request #94
Opened 2023-10-26 11:53 UTC by kkgowtham-engg-sdk

### Jira Ticket
https://moengagetrial.atlassian.net/browse/MOEN-27473

### Description
Google Policy - Delete User Details API

2023-10-30 06:17 UTC, umangmoe requested changes

2023-10-30 06:17 UTC, umangmoe commented on core/moengage_flutter_android/android/src/main/kotlin/com/moengage/flutter/MoEngageFlutterPlugin.kt
> +            pluginHelper.deleteUser(context,payload){
```kotlin
pluginHelper.deleteUser(context,payload) { data -> 
}
```

2023-10-30 06:17 UTC, umangmoe commented on core/moengage_flutter_android/android/src/main/kotlin/com/moengage/flutter/MoEngageFlutterPlugin.kt
> +            pluginHelper.deleteUser(context,payload){
Fix formatting

2023-10-30 06:17 UTC, umangmoe commented on core/moengage_flutter_android/android/src/main/kotlin/com/moengage/flutter/MoEngageFlutterPlugin.kt
> +        }catch (t:Throwable){
fix formatting

2023-10-30 06:17 UTC, umangmoe commented on core/moengage_flutter_android/lib/moengage_flutter_android.dart
> +  UserDeletionData _deSerializeDeleteUserData(String data, String appId) {
Move this to separate parser class. 
Add a unit test case for this.

2023-10-30 06:17 UTC, umangmoe commented on core/moengage_flutter_platform_interface/lib/src/model/user_deletion_data.dart
> +class UserDeletionData{
can we add a since tag?

2023-10-30 06:17 UTC, umangmoe commented on core/moengage_flutter_platform_interface/lib/src/moengage_flutter_platform_interface.dart
> +  /// Delete User Data
Mention this API is for Android only.

2023-10-30 06:17 UTC, umangmoe commented on geofence/moengage_geofence_android/android/build.gradle
> +    compileOnly("com.moengage:moe-android-sdk:12.10.00")
do we really need this change?

2023-10-30 06:17 UTC, umangmoe commented on inbox/moengage_inbox_android/android/build.gradle
>      implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
do we really need this change?

2023-10-30 06:17 UTC, umangmoe commented on core/moengage_flutter_platform_interface/lib/src/moengage_flutter_platform_interface.dart
> +  Future<UserDeletionData> deleteUser(String appId) =>
Is it standard to throw an unimplemented exception? I don't see it being thrown for other APIs that are specific to a platform.

2023-10-30 06:17 UTC, umangmoe commented on cards/moengage_cards_android/android/build.gradle
>      api("com.moengage:plugin-base-cards:1.0.1")
do we really need this change?

2023-10-30 06:17 UTC, umangmoe commented on core/moengage_flutter_android/android/src/main/kotlin/com/moengage/flutter/MoEngageFlutterPlugin.kt
> +                METHOD_NAME_DELETE_USER -> deleteUser(call,result)
fix formatting

2023-10-30 06:17 UTC, umangmoe commented on core/moengage_flutter_platform_interface/lib/src/model/user_deletion_data.dart
> +  /// True is user is deleted successfully
true if the user is deleted successfully, else false.

2023-10-30 06:17 UTC, umangmoe commented on example/android/app/build.gradle
>    testImplementation 'junit:junit:4.13.2'
can we use catalog in sample app instead?

2023-11-02 03:42 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_android/android/src/main/kotlin/com/moengage/flutter/MoEngageFlutterPlugin.kt
> +            val payload: String = methodCall.arguments.toString()
Updated

2023-11-02 03:43 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_android/android/src/main/kotlin/com/moengage/flutter/MoEngageFlutterPlugin.kt
> +            if (methodCall.arguments == null) return
Added

2023-11-02 03:43 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_android/android/src/main/kotlin/com/moengage/flutter/MoEngageFlutterPlugin.kt
> +            pluginHelper.deleteUser(context,payload){
Fixed

2023-11-02 03:43 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_android/android/src/main/kotlin/com/moengage/flutter/MoEngageFlutterPlugin.kt
> +        }catch (t:Throwable){
Fixed

2023-11-02 03:43 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_android/lib/moengage_flutter_android.dart
> +  UserDeletionData _deSerializeDeleteUserData(String data, String appId) {
Moved to PayloadMapper Class. Added Unit Test

2023-11-02 03:43 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_platform_interface/lib/src/model/user_deletion_data.dart
> +class UserDeletionData{
Added

2023-11-02 03:47 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_platform_interface/lib/src/moengage_flutter_platform_interface.dart
> +  /// Delete User Data
Already added for Public API. 
Usually we don't mention for specific Platform only in Platform interface package. So not required I think.

2023-11-02 03:47 UTC, kkgowtham-engg-sdk commented on geofence/moengage_geofence_android/android/build.gradle
> +    compileOnly("com.moengage:moe-android-sdk:12.10.00")
Reverted

2023-11-02 03:47 UTC, kkgowtham-engg-sdk commented on inbox/moengage_inbox_android/android/build.gradle
>      implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
Reverted

2023-11-02 04:06 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_platform_interface/lib/src/moengage_flutter_platform_interface.dart
> +  Future<UserDeletionData> deleteUser(String appId) =>
Both the ways are common in Federated Plugin. 
1) If we don't throw error, we need to override and add a log in web and ios package classes as it is abstract method. And release might be required for those two packages as well. 
[Example](https://github.com/firebase/flutterfire/blob/master/packages/firebase_analytics/firebase_analytics_platform_interface/lib/src/platform_interface/platform_interface_firebase_analytics.dart)

2023-11-02 04:06 UTC, kkgowtham-engg-sdk commented on cards/moengage_cards_android/android/build.gradle
>      api("com.moengage:plugin-base-cards:1.0.1")
Reverted

2023-11-02 04:07 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_android/android/src/main/kotlin/com/moengage/flutter/MoEngageFlutterPlugin.kt
> +                METHOD_NAME_DELETE_USER -> deleteUser(call,result)
Updated

2023-11-02 04:07 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_platform_interface/lib/src/model/user_deletion_data.dart
> +  /// True is user is deleted successfully
Updated

2023-11-02 04:11 UTC, kkgowtham-engg-sdk commented on example/android/app/build.gradle
>    testImplementation 'junit:junit:4.13.2'
Will raise a separate PR for this.

2023-11-02 05:09 UTC, umangmoe commented on core/moengage_flutter_android/android/src/main/kotlin/com/moengage/flutter/MoEngageFlutterPlugin.kt
> +            result.error(ERROR_CODE_DELETE_USER, t.message.toString(), null)
Are we sure we want to send the stacktrace for internal error to the client application? Shouldn't be a generic message?

2023-11-02 05:10 UTC, umangmoe commented on core/moengage_flutter_android/test/dataprovider/json_data.dart
> +    "appId": "DAO6UGZ73D9RTK8B5W96TPYN"
remove the app-id, keep a dummy value

2023-11-02 05:10 UTC, umangmoe commented on core/moengage_flutter_android/test/dataprovider/json_data.dart
> +const String appId = 'DAO6UGZ73D9RTK8B5W96TPYN';
remove app-id, keep a dummy value

2023-11-02 05:13 UTC, umangmoe commented on core/moengage_flutter_android/test/dataprovider/data_provider.dart
> +    accountMeta: AccountMeta('DAO6UGZ73D9RTK8B5W96TPYN'), isSuccess: true);
remove appi-id, use a dummy value

2023-11-02 06:06 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_android/test/dataprovider/data_provider.dart
> +    accountMeta: AccountMeta('DAO6UGZ73D9RTK8B5W96TPYN'), isSuccess: true);
Updated

2023-11-02 06:06 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_android/test/dataprovider/json_data.dart
> +const String appId = 'DAO6UGZ73D9RTK8B5W96TPYN';
Updated

2023-11-02 06:06 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_android/test/dataprovider/json_data.dart
> +    "appId": "DAO6UGZ73D9RTK8B5W96TPYN"
Updated

2023-11-02 06:10 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter_android/android/src/main/kotlin/com/moengage/flutter/MoEngageFlutterPlugin.kt
> +            result.error(ERROR_CODE_DELETE_USER, t.message.toString(), null)
Updated with Generic Error Message.

2023-11-27 09:28 UTC, merged