MOEN-28397: Added support for array in user attributes
moengage/Flutter-SDK pull request #99
Opened 2023-11-29 07:23 UTC by msoumya-engg-sdk

### Jira Ticket

https://moengagetrial.atlassian.net/browse/MOEN-28397

### Description

1. Support arrays of Strings, Ints, Doubles, and Numbers in flutter.
2. The array must contain non-optional items. Mixing above types with null will result in attribute not getting tracked.

2023-11-29 08:30 UTC, RakshithaAcharya requested changes

2023-11-29 08:30 UTC, RakshithaAcharya commented on core/moengage_flutter/CHANGELOG.md
> +- Added support for array in user attributes
@msoumya-engg-sdk update the packages to latest SDK Version

2023-11-30 04:03 UTC, kkgowtham-engg-sdk commented on example/lib/main.dart
> +                      ['This', 'is', 'an', 'array', 'of', 'strings']);
Can we set a heterogeneous array as well in the example? To make sure it is not tracked.

2023-11-30 04:06 UTC, kkgowtham-engg-sdk commented on core/moengage_flutter/lib/src/moengage_flutter.dart
>      }
I think we can add all the supported types in API documentation. Thoughts?

2023-11-30 04:30 UTC, RakshithaAcharya requested changes

2023-11-30 04:30 UTC, RakshithaAcharya commented on inbox/moengage_inbox_ios/CHANGELOG.md
> +- Plugin Inbox Version Updated to `2.5.0`
@msoumya-engg-sdk moving forward, do mention the version of native sdk instead of plugin base as client won't we aware of pluginbase

2023-12-04 06:14 UTC, msoumya-engg-sdk commented on core/moengage_flutter/lib/src/moengage_flutter.dart
>      }
Added types supported in API doc.

2023-12-04 06:15 UTC, msoumya-engg-sdk commented on example/lib/main.dart
> +                      ['This', 'is', 'an', 'array', 'of', 'strings']);
Added failure test cases.

2023-12-04 06:40 UTC, kkgowtham-engg-sdk approved these changes

2023-12-04 06:51 UTC, RakshithaAcharya approved these changes

2023-12-06 12:43 UTC, merged